# Generated by Django 3.0.7 on 2020-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20200609_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='cost',
            field=models.IntegerField(default=400),
        ),
    ]
