# Generated by Django 3.0.7 on 2020-06-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_bus_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bus',
            new_name='BusDet',
        ),
    ]
