# Generated by Django 3.0.7 on 2020-06-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_auto_20200615_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_1', models.BooleanField(default=False)),
                ('seat_2', models.BooleanField(default=False)),
                ('seat_3', models.BooleanField(default=False)),
                ('seat_4', models.BooleanField(default=False)),
                ('seat_5', models.BooleanField(default=False)),
                ('seat_6', models.BooleanField(default=False)),
                ('seat_7', models.BooleanField(default=False)),
                ('seat_8', models.BooleanField(default=False)),
                ('seat_9', models.BooleanField(default=False)),
                ('seat_10', models.BooleanField(default=False)),
                ('seat_11', models.BooleanField(default=False)),
                ('seat_12', models.BooleanField(default=False)),
                ('seat_13', models.BooleanField(default=False)),
                ('seat_14', models.BooleanField(default=False)),
                ('seat_15', models.BooleanField(default=False)),
                ('seat_16', models.BooleanField(default=False)),
                ('seat_17', models.BooleanField(default=False)),
                ('seat_18', models.BooleanField(default=False)),
                ('seat_19', models.BooleanField(default=False)),
                ('seat_20', models.BooleanField(default=False)),
                ('seat_21', models.BooleanField(default=False)),
                ('seat_22', models.BooleanField(default=False)),
                ('seat_23', models.BooleanField(default=False)),
                ('seat_24', models.BooleanField(default=False)),
                ('seat_25', models.BooleanField(default=False)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.BusDet')),
            ],
        ),
    ]
