# Generated by Django 3.0.7 on 2020-06-20 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdet',
            name='seats',
            field=models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
    ]
