# Generated by Django 3.0.7 on 2020-06-21 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20200621_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_26',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_27',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_28',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_29',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_31',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_32',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_33',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_34',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_35',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='busdet',
            name='seats',
            field=models.IntegerField(default=35, validators=[django.core.validators.MaxValueValidator(35), django.core.validators.MinValueValidator(0)]),
        ),
    ]
