# Generated by Django 3.0.7 on 2020-06-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_auto_20200621_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
